### ISSUE TITLE
yo mate i am looking for a script that does this 

### ISSUE THREAD

**Issue by minanagehsalalma** [n0obit4/WDFK#1]
print the available wifi adapters to choose from then ask if they want to scan all channels or a specific channel then after the scan is ended using ctrl + c allow them to choose from the ap list and of course every ap that have clients on it should have a star in the start of the line... to run airodump-ng on it.

it's simple and widely available but i can't seem to just find this part only.

**Comment by n0obit4** [comment]
Look the new release [v1.1](https://github.com/n0obit4/WDFK) and tell me if that is what you want?

**Comment by minanagehsalalma** [comment]
> Look the new release [v1.1](https://github.com/n0obit4/WDFK) and tell me if that is what you want?

@n0obit4 lookin at the code it seems that it indeed does ..

thanks mate , might test it out later :)

**Comment by n0obit4** [comment]
Perfect
